// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnhwyzatwocjkkikldve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJuaHd5emF0d29jamtraWtsZHZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzOTUyMDEsImV4cCI6MjA1NDk3MTIwMX0.9S_bB3LqwJ_iS8NCNmSPcbld5yTfaF1EvnNEkun9u6Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);